name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
#   release:
#     types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    # if: ${{ github.repository_owner == 'BnanZ0' }}
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: 'ok-nte-win32-China-setup.exe'
          mirrorchyan_rid: ok-nte
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: BnanZ0
          repo: ok-nte
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}